# Generated by Django 3.2.25 on 2025-01-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250104_0039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='ClothingSizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='clothing_sizes',
            field=models.ManyToManyField(to='core.ClothingSizes'),
        ),
    ]
