# Generated by Django 3.2.25 on 2025-01-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_clothing_sizes_product_clothingsizes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClothingSizes',
            new_name='ClothingSize',
        ),
    ]
