# Generated by Django 3.2.25 on 2025-01-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_clothingsizes_clothingsize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='clothingSizes',
            new_name='clothing_sizes',
        ),
    ]
