# Generated by Django 4.0.10 on 2025-02-21 19:19

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='clothing_sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time_minutes',
        ),
        migrations.AddField(
            model_name='product',
            name='spotify',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='youtube',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link_youtube', models.TextField()),
                ('link_spotify', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(null=True, upload_to=core.models.product_image_file_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
