# Generated by Django 4.0.10 on 2025-02-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_product_clothing_sizes_remove_product_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Episode'},
        ),
    ]
